{
 "title": "Daemon observability",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "nodename",
    "label": "Node Name",
    "query": "label_values(systemd_unit_state, job)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(systemd_unit_state{job=~\"$nodename\"}, vm_name)"
   },
   {
    "name": "instance",
    "label": "Instance (IP:port)",
    "query": "label_values(systemd_unit_state{job=~\"$nodename\", vm_name=~\"$job\"}, instance)"
   },
   {
    "name": "svc",
    "label": "Service",
    "query": "label_values(systemd_unit_state{name=~\"academia-info.service|common-service.service|ib-auth-server-1.service|mobile-recharge.service|admin-server.service|core-correct.service|ib-auth-server-education.service|nagad-service.service|api-gateway-0.service|education-system.service|ib-mobile-verify-auth-server-0.service|nda.service|api-gateway.service|filesystem.service|ib-mobile-verify-auth-server-education.service|notification-service.service|bank-details|api.service|ib-api-0.service|ib-pin-server-0.service|otp-control.service|bill-collector.service|ib-api-1.service|ib-reconcile.service|vault.service|bkash-service-0.service|ib-api-2.service|ib-report.service|voice-banking-middleware.service|bkash-service-1.service|ib-api-3.service|ib-user-security-management.service|bkash-service-2.service|ib-api-v2.service|jboss.service|cbs-middleware-api.service|ib-auth-server-0.service|middleware-system-control.service|nginx-ui.service|nginx.service|node_exporter.service|process_exporter.service|docker.service|docker.socket|prometheus.service|grafana-server.service|ssh.service\", job=~\"$nodename\", instance=~\"$instance\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Services (Available)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (name) (systemd_unit_state{name=~\"academia-info.service|common-service.service|ib-auth-server-1.service|mobile-recharge.service|admin-server.service|core-correct.service|ib-auth-server-education.service|nagad-service.service|api-gateway-0.service|education-system.service|ib-mobile-verify-auth-server-0.service|nda.service|api-gateway.service|filesystem.service|ib-mobile-verify-auth-server-education.service|notification-service.service|bank-details|api.service|ib-api-0.service|ib-pin-server-0.service|otp-control.service|bill-collector.service|ib-api-1.service|ib-reconcile.service|vault.service|bkash-service-0.service|ib-api-2.service|ib-report.service|voice-banking-middleware.service|bkash-service-1.service|ib-api-3.service|ib-user-security-management.service|bkash-service-2.service|ib-api-v2.service|jboss.service|cbs-middleware-api.service|ib-auth-server-0.service|middleware-system-control.service|nginx-ui.service|nginx.service|node_exporter.service|process_exporter.service|docker.service|docker.socket|prometheus.service|grafana-server.service|ssh.service\", job=~\"$nodename\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Services Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (name) (systemd_unit_state{name=~\"academia-info.service|common-service.service|ib-auth-server-1.service|mobile-recharge.service|admin-server.service|core-correct.service|ib-auth-server-education.service|nagad-service.service|api-gateway-0.service|education-system.service|ib-mobile-verify-auth-server-0.service|nda.service|api-gateway.service|filesystem.service|ib-mobile-verify-auth-server-education.service|notification-service.service|bank-details|api.service|ib-api-0.service|ib-pin-server-0.service|otp-control.service|bill-collector.service|ib-api-1.service|ib-reconcile.service|vault.service|bkash-service-0.service|ib-api-2.service|ib-report.service|voice-banking-middleware.service|bkash-service-1.service|ib-api-3.service|ib-user-security-management.service|bkash-service-2.service|ib-api-v2.service|jboss.service|cbs-middleware-api.service|ib-auth-server-0.service|middleware-system-control.service|nginx-ui.service|nginx.service|node_exporter.service|process_exporter.service|docker.service|docker.socket|prometheus.service|grafana-server.service|ssh.service\", state=\"active\", job=~\"$nodename\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Services Down",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (name) (systemd_unit_state{name=~\"academia-info.service|common-service.service|ib-auth-server-1.service|mobile-recharge.service|admin-server.service|core-correct.service|ib-auth-server-education.service|nagad-service.service|api-gateway-0.service|education-system.service|ib-mobile-verify-auth-server-0.service|nda.service|api-gateway.service|filesystem.service|ib-mobile-verify-auth-server-education.service|notification-service.service|bank-details|api.service|ib-api-0.service|ib-pin-server-0.service|otp-control.service|bill-collector.service|ib-api-1.service|ib-reconcile.service|vault.service|bkash-service-0.service|ib-api-2.service|ib-report.service|voice-banking-middleware.service|bkash-service-1.service|ib-api-3.service|ib-user-security-management.service|bkash-service-2.service|ib-api-v2.service|jboss.service|cbs-middleware-api.service|ib-auth-server-0.service|middleware-system-control.service|nginx-ui.service|nginx.service|node_exporter.service|process_exporter.service|docker.service|docker.socket|prometheus.service|grafana-server.service|ssh.service\", state=\"inactive\", job=~\"$nodename\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Service Current Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "systemd_unit_state{name=~\"academia-info.service|common-service.service|ib-auth-server-1.service|mobile-recharge.service|admin-server.service|core-correct.service|ib-auth-server-education.service|nagad-service.service|api-gateway-0.service|education-system.service|ib-mobile-verify-auth-server-0.service|nda.service|api-gateway.service|filesystem.service|ib-mobile-verify-auth-server-education.service|notification-service.service|bank-details|api.service|ib-api-0.service|ib-pin-server-0.service|otp-control.service|bill-collector.service|ib-api-1.service|ib-reconcile.service|vault.service|bkash-service-0.service|ib-api-2.service|ib-report.service|voice-banking-middleware.service|bkash-service-1.service|ib-api-3.service|ib-user-security-management.service|bkash-service-2.service|ib-api-v2.service|jboss.service|cbs-middleware-api.service|ib-auth-server-0.service|middleware-system-control.service|nginx-ui.service|nginx.service|node_exporter.service|process_exporter.service|docker.service|docker.socket|prometheus.service|grafana-server.service|ssh.service\", job=~\"$nodename\", instance=~\"$instance\"} == 1"
    }
   ]
  },
  {
   "title": "Service History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "systemd_unit_state{name=~\"$svc\", job=~\"$nodename\", instance=~\"$instance\", state=\"active\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}